# Generated by Django 3.1.2 on 2020-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_url', models.URLField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('index', models.IntegerField(unique=True)),
                ('audio_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('index', models.IntegerField(unique=True)),
                ('audio_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
                ('playlists', models.ManyToManyField(to='audios.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('index', models.IntegerField(unique=True)),
                ('audio_url', models.URLField()),
                ('transcript', models.TextField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='audios.Track'),
        ),
    ]
