# Generated by Django 2.1.4 on 2020-10-15 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_auto_20201015_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='audio_url',
            field=models.URLField(help_text='URL of audios.'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Name of the language.', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='published',
            field=models.BooleanField(default=True, help_text='Decide whether this language is ready for users to see.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='active',
            field=models.BooleanField(default=True, help_text='Status that indicates if this playlist is being actively updated.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='audio_url',
            field=models.URLField(help_text='URL to the audio directory associated with the playlist.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='index',
            field=models.IntegerField(help_text='The position of the playlist within a topic.', unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='published',
            field=models.BooleanField(default=True, help_text='Decide to show or hide the playlist from the users.'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(help_text='The title of the playlist.', max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(help_text='A list of all the tracks this playlist contains.', to='audios.Track'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True, help_text='Status that indicates if this topic is being actively updated.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='audio_url',
            field=models.URLField(help_text='URL to the audio directory associated with the topic.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='index',
            field=models.IntegerField(help_text='The order/position of the topic within the interface.', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='playlists',
            field=models.ManyToManyField(help_text='A list of all the playlists this topic contains.', to='audios.Playlist'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='published',
            field=models.BooleanField(default=True, help_text='Decide to show or hide the topic from the users.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='The name of the topic.', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='active',
            field=models.BooleanField(default=True, help_text='Status that indicates if this track is being actively updated.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(help_text='URL to the audio file that goes with this track.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='When the track was created.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(help_text='Duration in seconds.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='index',
            field=models.IntegerField(help_text='The position of the track within a playlist.', unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='published',
            field=models.BooleanField(default=True, help_text='Decide whether this track is ready for users to see.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(help_text='Title of the track.', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='transcript',
            field=models.TextField(help_text='A string/text transcript that goes along with the audio.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='When the track was last updated.'),
        ),
    ]
