# Generated by Django 2.1.4 on 2020-10-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_auto_20201015_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactivate to temporarily delete playlist and reactivate to recover.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactivate to temporarily delete topic and reactivate to recover.'),
        ),
        migrations.AlterField(
            model_name='track',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactivate to temporarily delete track and reactivate to recover.'),
        ),
    ]
